name: Run Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "target environment"
        required: true
        default: "dev"
        options:
          - dev
          - prod
      product:
        required: true
        type: choice
        default: "BEAM"
        options:
          - DTC
          - ATVE
          - BEAM
        description: "ex. DTC, ATVE, BEAM"
      client:
        required: true
        type: choice
        options:
          - android
          - androidtv
          - appletv
          - firetab
          - firetv
          - ios
          - ipad
          - lg
          - roku
          - samsung
          - web
          - xbox
        default: "web"
        description: "client under test ex. android, roku, web, appletv etc"
      test_type:
        required: true
        default: "integration"
        description: "ex. integration, nightly, gqa_core_test, regression"
      region:
        required: true
        default: "us"
        description: "region country/city code as set in SSM parameters (e.g us, gb, br)"
      feature:
        description: "feature file (ex. welcome_screen.feature)"
        required: false
      tag:
        description: 'cucumber tag for filtering scenarios to execute.'
        required: true

env:
  TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
  TESTRAIL_APIKEY: ${{ secrets.TESTRAIL_APIKEY }}
  NPM_REPOSITORY_USER: ${{ secrets.WBD_NPM_JFROG_RO_USERNAME }}
  NPM_REPOSITORY_TOKEN: ${{ secrets.WBD_NPM_JFROG_RO_TOKEN }}
  CUCUMBER_TAG: ${{ github.event.inputs.tag }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Git config email
        run: git config --local user.email publishbot@wbd.com

      - name: Git config name
        run: git config --local user.name publishbot

      - name: Create .npmrc
        run: cp .template.npmrc .npmrc

      - run: |
          npm install
          npm update @wbd/gqa-core
          npm list @wbd/gqa-core

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::463602674264:role/github-actions-oidc-power-user
          aws-region: us-east-2

      - name: Run Tests
        shell: bash
        run: |
          environment=${{ github.event.inputs.environment || 'dev' }}
          product=${{ github.event.inputs.product || 'BEAM' }}
          client=${{ github.event.inputs.client || 'web' }}
          test_type=${{ github.event.inputs.test_type || 'gqa_core_test' }}
          feature="${{ github.event.inputs.feature }}"
          region="${{ github.event.inputs.region || 'us' }}"

          if [ -z "$region" ]; then
            region='none'
          fi

          if [ -n "$feature" ]; then
            ./entrypoint.sh -e $environment -p $product -c $client -t $test_type -f $feature -r $region
          else
            ./entrypoint.sh -e $environment -p $product -c $client -t $test_type -r $region
          fi

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results

      - name: Generate test report
        if: always()
        shell: bash
        run: npx jake utils:report

      - name: Publish test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results
          retention-days: 5