name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      artifacts:
        description: 'artifacts reporting'
        required: false
        type: boolean
    push:
      branches:
      - main
      - test
      - dev    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipin-discovery/Demo-locust-github-action@main
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  "https://prod.playback.h264.io"
          USERS: "6"
          RATE: "6"
          RUNTIME: "10s"