name: Running Locust Load Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - aws
        - azure
      host:
        required: true
        type: string
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "  "
      endpoint:
        required: true
        type: string
        default: "integration"
        description: "endpoint"
      users:
        required: true
        type: string
        default: "5"
        description: "Number of users"
      spawn-rate:
        description: "spawn-rate"
        type: string
        required: true
        default: "5"
      run-time:
        description: 'run-time'
        type: string
        required: true
        default: "10s"
    push:
      branches:
      - main
      - test
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipin-discovery/Demo-locust-github-action@main
        with:
          LOCUSTFILE: "${LOCUSTFILE}"
          URL:  "${URL}"
          USERS: "${RATE}"
          RATE: "${USERS}"
          RUNTIME: "${RUNTIME}"
